apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 921562758039.dkr.ecr.ap-southeast-2.amazonaws.com/myapp-repo
  newName: 921562758039.dkr.ecr.ap-southeast-2.amazonaws.com/myapp-repo
  newTag: b3abac7d
resources:
- ../../base
patchesStrategicMerge:
- myapp-deployment-patch.yaml
- myapp-service-patch.yaml
